name: Publish Helm Chart

on:
  workflow_dispatch:
  repository_dispatch:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
    types: [chart]
    # Expects the following JSON payload:
    # {
    #   "client_payload": {
    #     "since_sha": "332548093a62aeacd5e3737fcbe0d019055a1fb5"
    #   }
    # }

permissions:
  contents: read

env:
  TARGET_ORG: actions-runner-controller
  TARGET_REPO: charts-test-repo
  TARGET_BRANCH: main

jobs:
  publish-chart:
    name: Publish Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: actions/actions-runner-controller
          ref: ${{ github.event.client_payload.since_sha }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.ACTIONS_ACCESS_APP_ID }}
          application_private_key: ${{ secrets.ACTIONS_ACCESS_PK }}
          organization: ${{ env.TARGET_ORG }}

      - name: Create config file
        run: |
          cat << EOF > config.yaml
          owner: ${{ env.TARGET_ORG }}
          git-repo: ${{ env.TARGET_REPO }}
          pages-branch: ${{ env.TARGET_BRANCH }}
          EOF

      - name: Install chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          install_only: true
          install_dir: ${{ github.workspace }}/bin

      - name: Run chart-releaser
        run: |
          cr package \
            ${{ github.workspace }}/charts/actions-runner-controller/ \
            --config ${{ github.workspace }}/config.yaml \
            --package-path .cr-release-packages

          cr upload \
            --package-path .cr-release-packages \
            --config ${{ github.workspace }}/config.yaml \
            --token ${{ steps.get_workflow_token.outputs.token }} \
            || true

      - name: Checkout pages repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.TARGET_ORG }}/${{ env.TARGET_REPO }}
          path: ${{ env.TARGET_REPO }}
          ref: ${{ env.TARGET_BRANCH }}
          token: ${{ steps.get_workflow_token.outputs.token }}

      - name: Push index.yaml
        run: |
          cr index \
            --config ${{ github.workspace }}/config.yaml \
            --index-path ${{ github.workspace }}/${{ env.TARGET_REPO }} \
            --push \
            --token ${{ steps.get_workflow_token.outputs.token }}
        working-directory: ./${{ env.TARGET_REPO }}
