name: Publish Canary Image

# This workflow anticipates a repository_dispatch event from the actions/actions-runner-controller repository
on:
  repository_dispatch:
    types: [canary]
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
    # Expects the following JSON payload:
    # {
    #   "client_payload": {
    #     "sha": "84104de74b8e9e555f530d40d8f33cc9471716f5"
    #     "push_to_registries": true
    #   }
    # }

# https://docs.github.com/en/rest/overview/permissions-required-for-github-apps
permissions:
  contents: read
  packages: write

env:
  TARGET_ORG: actions-runner-controller
  TARGET_REPO: actions-runner-controller

jobs:
  canary-build:
    name: Build and Publish Canary Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Environment
        uses: ./.github/actions/setup-docker-environment
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          ghcr_username: ${{ github.actor }}
          ghcr_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: actions/actions-runner-controller
          path: arc/
          ref: ${{ github.event.client_payload.sha }}

      - name: Get Short SHA
        id: vars
        run: |
          echo "short_sha=$(echo ${{ github.event.client_payload.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      # Considered unstable builds
      # See Issue #285, PR #286, and PR #323 for more information
      # If push_to_registries is not provided, we'll default to false
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          file: arc/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: VERSION=canary-${{ github.steps.vars.outputs.short_sha }}
          # push: ${{ github.event.client_payload.push_to_registries || false }}
          push: false
          tags: |
            ${{ secrets.DOCKER_USER }}/actions-runner-controller:canary
            ghcr.io/${{ env.TARGET_ORG }}/${{ env.TARGET_REPO }}:canary
          cache-from: type=gha,scope=arc-canary
          cache-to: type=gha,mode=max,scope=arc-canary
