name: Publish Helm Chart

on:
  workflow_dispatch:
  repository_dispatch:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
    types: [chart]
    # Expects the following JSON payload:
    # {
    #   "client_payload": {
    #     "since_sha": "332548093a62aeacd5e3737fcbe0d019055a1fb5"
    #   }
    # }

permissions:
  contents: read

env:
  TARGET_ORG: actions-runner-controller
  TARGET_REPO: charts-test-repo
  TARGET_BRANCH: main

jobs:
  publish-chart:
    name: Publish Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: actions/actions-runner-controller

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.ACTIONS_ACCESS_APP_ID }}
          application_private_key: ${{ secrets.ACTIONS_ACCESS_PK }}
          organization: ${{ env.TARGET_ORG }}

      - name: Create config file
        run: |
          echo <<EOF > config.yaml
          owner: ${{ env.TARGET_ORG }}
          git-repo: ${{ env.TARGET_REPO }}
          pages-branch: ${{ env.TARGET_BRANCH }}
          commit: ${{ github.event.client_payload.since_sha }}
          EOF

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ steps.get_workflow_token.outputs.token }}"

      - name: troubleshoot
        uses: mxschmitt/action-tmate@v3